# Project-wide Gradle settings.

# JVM arguments for the Gradle daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Performance
org.gradle.configuration-cache=true

# Kotlin
kotlin.code.style=official

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Suppress warnings for compileSdk newer than AGP's tested range
android.suppressUnsupportedCompileSdk=35